### ISSUE TITLE
Templates?

### ISSUE THREAD

**Issue by jankap** [anoopkcn/obsidian-reference-map#10]
Is it possible to modify the view via templates? I would love to add a Zotero link for example. The DOI or bibtex Link could be used to open the corresponding file via the url `zotero://select/items/@[citekey]`

Thanks :)

**Comment by anoopkcn** [comment]
Hi, At the moment, you cant modify the view. However, I have added the option to open the reference in Zotero; You will have to toggle this option in the Settings tab. 

<img width="722" alt="Screenshot 2023-01-11 at 19 33 08" src="https://user-images.githubusercontent.com/14111873/211889945-c014d0d4-df35-41db-a047-abd017e71a46.png">

Once enabled, the `citekey` will be shown after the author in the index card; upon clicking it, the reference will be shown in the Zotero library. 

<img width="319" alt="Screenshot 2023-01-11 at 19 38 09" src="https://user-images.githubusercontent.com/14111873/211890261-99d220ac-0e9d-4b86-8a37-9456f74b75b2.png">

Reference Map supports the [Obsidian-style-settings](https://github.com/mgmeyers/obsidian-style-settings) plugin if you would like to customize the style of the link.

**Comment by jankap** [comment]
Works like a charm, thank you!
