### ISSUE TITLE
Error when use citekey on macOS 

### ISSUE THREAD

**Issue by jxpeng98** [anoopkcn/obsidian-reference-map#11]
Hello,

Many thanks for your excellent plugin!

I try to use citekey to build the reference map. However, it has an issue with the output.
![mQx5gn](https://cdn.jsdelivr.net/gh/jxpeng98/imagerepo@main/2023/01/mQx5gn.png)

It can only works with some citations. 
![ZNzevv](https://cdn.jsdelivr.net/gh/jxpeng98/imagerepo@main/2023/01/ZNzevv.png)

Here is the setting of the plugin:
![ShN7tX](https://cdn.jsdelivr.net/gh/jxpeng98/imagerepo@main/2023/01/ShN7tX.png)

I am sure that cited citekeys are included in the reference file. 

May I know how to solve this problem?

Many thanks!

**Comment by anoopkcn** [comment]
Hi, Citekey are used to get the ID(Such as DOI)of the paper from a Zotero library. If there are no DOIs present for a paper in the Zotero library, it won't show the results. Can you make sure the reference you are using has DOI's or similar ID's present in the Zotero library?  There is a Zotero plugin called `DOI manager`, which solves DOI-related issues for Zotero. 

IF the DOI is present in Zotero and it is still not loading(which I doubt would be the case) then we can trouble shoot this problem.

**Comment by anoopkcn** [comment]
This is fixed. Now, if there are non-valid DOIs in Zotero, it will not show the index card for that reference, but it will show the others with valid DOIs. Please get the latest release verison

**Comment by jxpeng98** [comment]
Hi @anoopkcn, 

Thanks for your reply and the suggested plugin!

Yes, you are right. It is the problem of `DOI`. Some references in my library do not have available `DOI`, so I cannot have the reference map. It can be solved with the [DOI manager](https://github.com/bwiernik/zotero-shortdoi). 

However, I find another issue with the available `DOI`. Some references cannot appear in the reference map. Here is an example with citekkey `@ball2020earnings`.

This is the metadata from `JSON`. 
```json
  {
    "id": "ball2020earnings",
    "accessed": {
        "date-parts": [
            [
                2022,
                4,
                13
            ]
        ]
    },
    "author": [
        {
            "family": "Ball",
            "given": "Ray"
        },
        {
            "family": "Gerakos",
            "given": "Joseph"
        },
        {
            "family": "Linnainmaa",
            "given": "Juhani T."
        },
        {
            "family": "Nikolaev",
            "given": "Valeri"
        }
    ],
    "citation-key": "ball2020earnings",
    "container-title": "Journal of Financial Economics",
    "container-title-short": "Journal of Financial Economics",
    "DOI": "10.1016/j.jfineco.2019.05.013",
    "ISSN": "0304-405X",
    "issue": "1",
    "issued": {
        "date-parts": [
            [
                2020,
                1,
                1
            ]
        ]
    },
    "language": "en",
    "page": "231-254",
    "source": "ScienceDirect",
    "title": "Earnings, retained earnings, and book-to-market in the cross section of expected returns",
    "type": "article-journal",
    "URL": "https://www.sciencedirect.com/science/article/pii/S0304405X19301382",
    "volume": "135"
},

```

Here is the information I get from sciencedirect:
![QG6xkg](https://cdn.jsdelivr.net/gh/jxpeng98/imagerepo@main/2023/01/QG6xkg.png)

`DOI` links are the same. However, It is still `No References Found`.
![Te7yRt](https://cdn.jsdelivr.net/gh/jxpeng98/imagerepo@main/2023/01/Te7yRt.png)

**Comment by anoopkcn** [comment]
The plugin looks at the [semanticscholar](https://www.semanticscholar.org/) database for references. This is one of the largest databases available.  
It looks like your paper is listed in semantic scholar with a different DOI; check [here](https://www.semanticscholar.org/paper/Earnings%2C-Retained-Earnings%2C-and-Book-to-Market-in-Ball-Gerakos/4bc02ef6f4d8103b782101585bf7983e9936e26d). it is listed with `DOI:10.2139/ssrn.2924798`

I don't know what the reason for this disparity.

**Comment by jxpeng98** [comment]
Hi, 
thanks for the reply. 

I see. This is the problem with their database. They do not update the DOI even if the paper has been published, especially for those journals that do not have partnerships with Semantic Scholar.

**Comment by anoopkcn** [comment]
I plan to add different database lookups before the stable release of the plugin.  This issue will be fixed in the future.

**Comment by jxpeng98** [comment]
I just found two web database for scholars. 

1. [Internet Archive](https://scholar.archive.org/). I checked the paper mentioned above, `DOI` is corrected. 
2. [fatcat!](https://fatcat.wiki/).

They provide API for searching.

**Comment by anoopkcn** [comment]
Thanks for the info. 
My action plan is to check the DOI registration agency and retrieve metadata from the respective agency. This, I think, is the most reliable way.  I will implement this soon

**Comment by jxpeng98** [comment]
Hi,

I find that ResearchGate can provide the updated DOI for published papers. Then, I find that CrossRef can have API for metadata retrieval. Here is the [instruction](https://api.crossref.org/swagger-ui/index.html) and [repo](https://github.com/CrossRef/rest-api-doc). May I know if is it possible to use this API for metadata and semanticscholar for open-access PDF?

Thanks!

**Comment by anoopkcn** [comment]
Crossref doesn't give you citations, also the references are sometimes inconsistent, also like you said the open-access pdf is absent. I can use crossref as a backup retrival API if the DOI is not found in the semantic scholar fetch. But some functionalities like open access pdf and citations will be missing. 
there is a relations field in crossref result which gives you if something is a preprint id the correct DOI but I found this to unreliable. 
So at the moment, I am weighing the options.
