### ISSUE TITLE
bibtex output different to SematicScholar cite (causing bib error)

### ISSUE THREAD

**Issue by grant-m-s** [anoopkcn/obsidian-reference-map#12]
As an example

[GAN Paper](https://www.semanticscholar.org/paper/Generative-Adversarial-Nets-Goodfellow-Pouget-Abadie/54e325aee6b2d476bbbb88615ac15e251c6e8214) gives:
@inproceedings{Goodfellow2014GenerativeAN,
  title={Generative Adversarial Nets},
  author={Ian J. Goodfellow and Jean Pouget-Abadie and Mehdi Mirza and Bing Xu and David Warde-Farley and Sherjil Ozair and Aaron C. Courville and Yoshua Bengio},
  booktitle={NIPS},
  year={2014}
}

whereas your output is:
@['JournalArticle', 'Conference']{Goodfellow2014GenerativeAN,
 author = {Ian J. Goodfellow and Jean Pouget-Abadie and Mehdi Mirza and Bing Xu and David Warde-Farley and Sherjil Ozair and Aaron C. Courville and Yoshua Bengio},
 booktitle = {NIPS},
 pages = {2672-2680},
 title = {Generative Adversarial Nets},
 year = {2014}
}

seem like all of the @#### are not coming out correct.

Not sure if thats an API issue but currently they're not usable in bib files

Thanks again for the great plugin.

**Comment by anoopkcn** [comment]
Hi, Currently, the API returns the Bibtex entry types as a list of possible types. This is what I return as the `{{bibtex}}` variable.  
But maybe I can add an option in the settings to standardize the BibTex, so I can choose one of the entry types (Example: `JournalArticle` from `@['JournalArticle', 'Conference']`) and reconstruct the BibTex. At least at the moment, this is the solution I am thinking about.

**Comment by grant-m-s** [comment]
There is a [standard](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#BibTeX) for them so it could come down to checking which required files do you have and assign from there. Not sure if that's overkill though.

**Comment by anoopkcn** [comment]
Yes, I can look for the standard type if present I will construct the bib with that if not I can type it as `misc`. What do you think?

**Comment by grant-m-s** [comment]
I think that would work fine. Strange that they don't just send it as presented on the site.

**Comment by anoopkcn** [comment]
I pushed the changes to the new release. An option to standardize the bibtex should be available now in the settings tab.

**Comment by grant-m-s** [comment]
So they are working, however I noticed a few things:

- JournalArticle seems to be alias for article and so should probably be changed to that always.
- you check against "tech" and "report" which should be "techreport"
- Because you're matching with the first in the list, it doesn't necessarily mean it'll match up with the original from the site. This also means that there's the possibility of the incorrect type when used in publications (although I'm not too sure of the implications of this given the reference is still there). What could happen is that due to each bibtex entry type having different required (and optional) fields, a mislabeled one may be missing key information on the citation.

Besides that, it is now correctly useable in bib files.

**Comment by anoopkcn** [comment]
I fixed the issues you mentioned. The `JournalArticle`  should now be parsed as `article` and `None` type to `misc` 
I will try to look for a better solution, but this should work in the mean time.
