### ISSUE TITLE
unable to add paper when using citekey

### ISSUE THREAD

**Issue by irzhegalova** [anoopkcn/obsidian-reference-map#14]
Hey, it's me again :)
Is it me or have I found a weird bug? From yesterday RefMap is unable to recognize papers using citekey, although it is in my Zotero library.
Let me show you an example (see attachment): when using doi.org/10.1016/j.arr.2022.101807 paper is recognized, when using [@raffinSedentaryBehaviorBiological2023] it is not.
![Screenshot from 2023-01-24 18-52-57](https://user-images.githubusercontent.com/56924948/214341926-d4a7b5f3-af35-4ae9-b7d4-825104847554.png)

![Screenshot from 2023-01-24 18-51-54](https://user-images.githubusercontent.com/56924948/214341704-7d3a10d0-8da1-4180-99d6-159b7b1dabf3.png)
![Screenshot from 2023-01-24 18-51-30](https://user-images.githubusercontent.com/56924948/214341709-2440fca6-5b43-453b-871e-b18288d095a6.png)

**Comment by anoopkcn** [comment]
Is the `DOI` field in the Zotero info pane of the paper empty? 
refmap can only find papers with `citekey` which has a valid doi in the Zotero metadata info. 

you can also check closed issue #11 to see if its similar

**Comment by irzhegalova** [comment]
Not really, doi is fine.
Some of them contain doi.org stuff, some do not.
I tried to go through closed issue and installed Doi formatter, reload Zotero and Obsidian, but still the problem persist.
But I also noticed that this problem only occur for papers added to Zotero AFTER installing RefMap, I tried few added before that and it went smoothly.

I also checked my json-library, it also looks exactly the same.

Another consideration is that for papers added after RefMap there is still doi inside {{id}} field so probably these events are linked somehow?

**Comment by anoopkcn** [comment]
>But I also noticed that this problem only occur for papers added to Zotero AFTER installing RefMap, I tried few added before that and it went smoothly.
Could it be that your CSL JSON file is not automatically updating (do you have background updated turned on in Better bibtex)?

**Comment by irzhegalova** [comment]
oh yes! I accidentally created two JSON-files and was updating one while using another. Thank you so much!
