### ISSUE TITLE
{{journal}} field should just be a journal title

### ISSUE THREAD

**Issue by quicly** [anoopkcn/obsidian-reference-map#16]
I am using journal titles as links in my reference cards and I wanted to use the template [[{{journal}}]], but unfortunately, at the moment, this field includes not only the title, but also additional information such as volume number and pagination. I believe it would be beneficial to have separate fields for the title and this additional information. 

Anyway, I appreciate the plugin as it automates many tasks that I previously had to do manually. Thanks!

**Comment by anoopkcn** [comment]
Hi @quicly,  Thanks for the suggestion. This is now added to the plugin. Please update the plugin(available at the community plugins tab in Obsidian) 
To account for the `volume` and `pages` there are new template variables available named `{{volume}}` and `{{pages}}`. The `{{journal}}` variable will not contain volume and pages form now on.
