### ISSUE TITLE
`findZoteroCiteKeyFromID` is unexpectedly case-sensitive

### ISSUE THREAD

**Issue by blakeNaccarato** [anoopkcn/obsidian-reference-map#18]
**Describe the bug**

`findZoteroCiteKeyFromID` is unexpectedly case-sensitive. If the case of the DOI does not match exactly (incl. case) in the Zotero record, then the citekey is not picked up.

It is possible that this affects other features, but I've only noticed it in this particular feature flag. This crops up because Semantic Scholar often has all-caps DOIs, and citations generated from journal sources e.g. using Zotero's browser plugin often generate lower- or mixed-case DOIs.

**To Reproduce**

Enable the specified feature, have an appropriately-updated/synced CSL-JSON from Zotero, and have one of your notes with `doi:{{doi}}` where `{{doi}}` _may differ in its case_ relative to the DOI field in the Zotero library/interface.

**Expected behavior**

The citekey chould be picked up regardless of differences in case between the Zotero item and the DOI specified in the Obsidian note.

**Platform**

 - OS: Windows 10
 - Obsidian v1.1.9
 - Plugin version v0.9.1

**Additional context**

I'm not very familiar with TypeScript/JavaScript, but I believe I've found the relevant parts of the codebase where changes would be made. This is probably related to the [`doi-regex` dependency](https://www.npmjs.com/package/doi-regex) matching "case insensitive for ASCII chars (but capitalised in the registry)".

It seems `setCiteKeyID` is called when `findZoteroCiteKeyFromID` is enabled, and at least the code path in `setCiteKeyID` corresponding to the `csl-json` adapter results in the match happening in a case-sensitive way. 

https://github.com/anoopkcn/obsidian-reference-map/blob/3ed6033a77d829c82b58de5331744b0fe2678d75/src/components/ReferenceMapList.tsx#L30-L43

https://github.com/anoopkcn/obsidian-reference-map/blob/3ed6033a77d829c82b58de5331744b0fe2678d75/src/utils.ts#L225-L240

**Comment by anoopkcn** [comment]
Hi @blakeNaccarato Thanks for reporting the bug. I resolved the issue. The fix will be available in the next release

**Comment by anoopkcn** [comment]
Hi, A new release is out with this change; please test it. If it works, you can close the issue.

**Comment by blakeNaccarato** [comment]
Just updated and tried it out. Looks like it works! I tried with a few items which were previously failing to find the citekey given DOIs. Thanks!
