### ISSUE TITLE
Support for citekeys in quotes

### ISSUE THREAD

**Issue by jsmm** [anoopkcn/obsidian-reference-map#19]
Citekeys in frontmatter, such as `@brown2018application`, are recognised by this plugin. They are not recognised if they are in quotes, `"@brown2018application"`, as it is necessary in YAML.

Would it be possible for this plugin to process quoted references?

**Comment by anoopkcn** [comment]
Hi, Check the latest release this issue should be fixed

**Comment by jsmm** [comment]
Great! Thanks so much.
