### ISSUE TITLE
Is there a way to know which citation (in the right panel) correspond to which "static reference list" (in the main text)

### ISSUE THREAD

**Issue by ernest67** [anoopkcn/obsidian-reference-map#20]
First of all, thank you so much for making this plug-in. This is definitely underrated and more people should be made aware of this awesome and useful plug-in, it transformed my workflow as a student who is doing a dissertation right now.

Currently, a list of citations appear in the right panel as long as you add a "static reference list" in the document. However, there is no way to know which citation correspond to which "static reference list" (unless you manually compare them). Is there a way, with a click of a button (e.g. clicking on the static reference list in the main body) can indicate which citation does it correspond to in the right panel? I think this will be especially useful when you have multiple citations in a document.

Thank you once again for creating this plug-in. I will recommend this to all of my friends and I wish that the number of users will grow exponentially.

**Comment by anoopkcn** [comment]
Hi @ernest67, thanks for using the plugin. I will think of something to solve this problem you are having. 

Good luck with your dissertation.

**Comment by anoopkcn** [comment]
I implemented this in the latest release version. Please check it out. It works as follows:

If you highlight an ID in the markdown file(either by drag selecting or double-clicking if it's a single word), it will highlight the corresponding index card in the reference map view(see figure)
<img width="1109" alt="Screenshot 2023-02-16 at 07 14 38" src="https://user-images.githubusercontent.com/14111873/219284928-d8d962db-bd43-4de9-af25-04c0218bc486.png">

This works in both source mode and preview mode

**Comment by ernest67** [comment]
Amazing, thank you so much!!! I really appreciate it!
