### ISSUE TITLE
Working on canvas?

### ISSUE THREAD

**Issue by jakeoung** [anoopkcn/obsidian-reference-map#21]
**Is your feature request related to a problem? Please describe.**

Reference doesn't work in Canvas files

**Describe the solution you'd like**

If there is a reference in a note in the canvas, I'd like this app to show the relevant references.

**Describe alternatives you've considered**

**Additional context**

**Comment by anoopkcn** [comment]
Hi @jakeoung, Thanks for the suggestion. This will be a feature in the future version of Reference Map. But in the current development plan this is not a priority. There will be new features added like online search and template support etc, will be added soon. So Canvas support will be after these features are implemented. 

Please note that I am the only developer for this plugin so far. Hopefully, more people are interested in the project and want to contribute to it.  So new features can be added more frequently.

**Comment by anoopkcn** [comment]
Canvas support is now available; please download the latest version. Thanks for the suggestion.
