### ISSUE TITLE
Finding citekey from links without prefix not working for Markdown links

### ISSUE THREAD

**Issue by blakeNaccarato** [anoopkcn/obsidian-reference-map#22]
I'd open a PR for this minor change, but I'm pointing out two potential changes and don't want to bundle them into one commit in case only one change or the other is necessary.

This bug is related to the functionality introduced in #17. In the linked code below, it looks like the `if (matches2) {...}` clause is indented too shallowly, blocking the rest of the function from returning.

https://github.com/anoopkcn/obsidian-reference-map/blob/3163c99d836e4f8a4916fe6fe7514ab2a3b5a86b/src/utils.ts#L125-L144

Also, maybe `citekeyRegex3` could be malformed? Per experimentation with https://regexr.com/, the `^` after the opening `\[` seems to be operating as a "beginning" rather than a "negated set". Below I suggest an update to that regex which matches my cursory testing, but you could be trying to negate something related to carats or slashes that I'm not quite understanding at the beginning of your regex.

```Plaintext
/\[^\^([^\s].*)\]\(/ig  # Current citekeyRegex3
/\[([^\s].*)\]\(/ig     # Suggested citekeyRegex3
```

Here is an example of one such Markdown link that is not being detected, but in fact all such links are undetected:

```Markdown
[aderaNonwettingDropletsHot2013](notes/aderaNonwettingDropletsHot2013.md)
```

**Platform**

 - OS: Windows 10 Pro 10.0.19045
 - Obsidian version v1.1.9
 - Plugin version v1.1.1

**Comment by anoopkcn** [comment]
Thanks for the report. You can make a pull request to the develop branch.

**Comment by anoopkcn** [comment]
The second change you mentioned with the regex is a bug indeed, but this regex should also avoid patterns like `[^1]`(for footnotes and `[^some block]` for transclusions.  This is what I was trying to negate with `^`. Mabe a bit more sophisticated regex is needed for this

**Comment by blakeNaccarato** [comment]
I see, I didn't realize that was a feature in Obsidian! I could modify `citekeyRegex3` and submit a PR, probably on Sunday, to this specification:

- Fix indentation while I'm in the vicinity
- Valid WikiLink-style links are already excluded by the previous match so...
- Match valid markdown links, extracting the citekey (pretty much done)
- Don't match footnotes
- Don't match [Obsidian-specific block references](https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note) aka transclusions

I could also add a few test cases to this to catch regressions, but I think this would require a test framework like https://github.com/facebook/jest to be in place. So this PR would just include the fix is all.

Is unit testing something you'd be interested in in the future, though? I might be interested in trying to implement this if you think it valuable.

**Comment by anoopkcn** [comment]
Great, I am planning on a release on Monday. So I can include this bugfix in the next release. 

I have yet to think about tests, but they would be a valuable addition for sure. So it would be nice if you could implement it(of course it is not time critical). 

It is nice to have more contributors to the project 🎉

**Comment by anoopkcn** [comment]
Hi just as a heads up. I made some prettier formatting rules in the `.prettierrc.json` file so that people who makes pull request doesn't have different rules setup. I formatted the whole repo using this rules and the changes are in the develop branch. You might want to pull before you a oull request.

**Comment by blakeNaccarato** [comment]
So, before matching on `citekeyRegex`, you appear to be sanitizing note content by a Regex that replaces one-or-more `]`, `)`, `*`, or \` (backtick) with ` ` (a single space) _prior_ to matching on the citekey regex. Could you help me understand that step?

https://github.com/anoopkcn/obsidian-reference-map/blob/3163c99d836e4f8a4916fe6fe7514ab2a3b5a86b/src/utils.ts#L118

And then in `citekeyRegex2` and `citekeyRegex3`, this sanitization isn't performed.

https://github.com/anoopkcn/obsidian-reference-map/blob/3163c99d836e4f8a4916fe6fe7514ab2a3b5a86b/src/utils.ts#L127

https://github.com/anoopkcn/obsidian-reference-map/blob/3163c99d836e4f8a4916fe6fe7514ab2a3b5a86b/src/utils.ts#L136

Once I fix up `citekeyRegex3` I can sprinkle in some explanatory comments near the other matches if you'd like. I will also indicate the test note content that I used to manually check matches, for later incorporation into whatever test framework.

**Comment by anoopkcn** [comment]
For the first point. Citekeys maynot necessarily be alpha-numeric so space is a character that I can use as a separator. 
For Example:
`**@Bank2021Autoencoders**` without line [118](https://github.com/anoopkcn/obsidian-reference-map/blob/3163c99d836e4f8a4916fe6fe7514ab2a3b5a86b/src/utils.ts#L118) would parse it as `@Bank2021Autoencoders**`. 
However this can also be done after parsing with sanitizeCiteKey function.  But then citekeys like `**@Bank2021Autoencoder**@anothercitekey` would be missed. 

For `citekeyRegex2` and `citekeyRegex3` it is assumed that there are no more than one citekey per link. So space splitting is not necessary.  Some examples: 
```
[[Papamakarios2021Normalizing | alternative text]]
[[Chen2019Neural]]
[Bank2021Autoencoders | alternative text](https:/somelinks)
```

**Comment by blakeNaccarato** [comment]
Thanks for the info. To avoid cluttering the Issue comments, I've set a roadmap for myself based on this information in a Draft PR. I'll mark it ready when it's good to go.

**Comment by blakeNaccarato** [comment]
Okay it took me awhile to get spun up and start troubleshooting this bug. My PR is red since I rebased and force pushed, but also I haven't committed any actual fix.

But I did create an example vault that goes along with the work on this Issue over at https://github.com/blakeNaccarato/obsidian-reference-map-test/tree/fix-md-link-regex. It exhibits some failing test cases for citekey detection in notes. There are more than just Markdown-style link failures, too, it seems. You can see some screenshots of passing and failing tests in the readme. Some failing tests:

- Markdown links with and without alt-text
- Consecutive citekeys prefixed with `@` in the same paragraph.
- A `mixed-citekey-tests.md` note that tries a bunch of citekey formats. It short-circuits and fails to see any.

These are likely genuine failures, although the way the tests are set up could be causing some breakage due to the test harness being too simple. I have it configured to point at a dummy CSL JSON reference library with some dummy references (with unique citekeys but they have the same dummy DOI). I've set up a few notes with varying content to see which ones cause the plugin to fail at detecting citekeys. I've offered to add you (@anoopkcn) as a collaborator over on that test repo in case you want to add or modify test cases. Note that the test case branch with the latest work is not the main branch.

Since I've never developed on an Obsidian plugin before (or even a JS project 😅), it took me a while to get spun up. I've got the test vault and the `npm run dev` process down now, so I should be able to delve deeper and do some debugging to see where it's going wrong. However, I've exhausted my hobby time this weekend, so unfortunately I won't be able to submit a PR before your next release. It may be as late as next weekend before I return to try and fix this bug.

If you end up deciding to fix this yourself, hopefully my test vault repo comes in handy for exercising the citekey detection code. Feel free to push to that repo and its branches however you like if it helps.

**Comment by anoopkcn** [comment]
The mixed citekey is failing because of the `.` character since this is a legal citekey character. So instead of it is recognizing `@somecitekey.` as a citekey. This is expected behaviour since `@title.1990.name` could be a citekey. 
As for the fix for the moment I will make the small edit and make a release version and we can look at the tests repo in detail for the next release. Thanks a lot.

**Comment by blakeNaccarato** [comment]
Sounds good. Yeah I underestimated the up-front cost to first-time setup, but I think I've got the hang of it now. I probably could've just fixed up the regex blindly but I guess I got carried away getting the test vault set up 😅.

**Comment by blakeNaccarato** [comment]
Also one more heads-up. I modified the test cases and found another breakage, that I think (for real this time) as a genuine breakage.

```Markdown
This is one reference [[citekey]]. This is another reference [[citekey2]].
```

Neither citekey gets picked up in this case. So, non-prefixed citekeys in WikiLinks will not be picked up in a paragraph with more than one of them. See the updated test cases for this breakage.

**Comment by anoopkcn** [comment]
Well, This demonstrates why we need test cases 😂. I think I fixed this issue. I pushed a patch version.

**Comment by blakeNaccarato** [comment]
I checked `master` against the test vault and all tests are passing now except for `wikilink-citekey-alt-text-no-space`, which would be hard to handle as long as citekeys can have pipe characters in them, e.g. `[[citekey|alt text]]`. So I think that covers the bulk of the issue! I don't have tests against block transclusions, however.

**Comment by blakeNaccarato** [comment]
I'm gonna close this issue now, since it looks like this fix is in the latest release. Thanks!
