### ISSUE TITLE
Detect citekeys in double brackets `[[]]`

### ISSUE THREAD

**Issue by jankap** [anoopkcn/obsidian-reference-map#27]
**Is your feature request related to a problem? Please describe.**
My workflow is to import relevant literature from Zotero to markdown files in Obsidian and naming the MD file identical as the bibtex citekey, e.g. `@author.shorttitle.year`. Linking to that document using double brackets, like `[[@author.shorttile.year]]` gets not detected as valid citekey and thus does not show up in the reference map. `[@author.shorttile.year]`

**Describe the solution you'd like**
It would be great to see `[[@author.shorttile.year]]` in the ref map.

Edit: got the problem, it was part of this sentence: `(see [[@tu.ARMABasedDigitalTwin.2021]])`. The last `)` breaks the detection. So it's not about the brackets, but what character follows.

**Comment by jankap** [comment]
Same for other signs like commas etc.

`[[@author.shorttilte.year]]` works, `[[@author.shorttilte.year]],` i.e. being part of an enumeration does not.

**Comment by jankap** [comment]
And another follow-up: Looks like the detection of double brackets kills the plugin, when there are links to images in the same document,

```
- [ ] Finalize metadata and import 
	- [ ] [[@qi.NovelTemperatureDrift.2022]]
	- [ ] [[@tu.ARMABasedDigitalTwin.2021]]

 ![[Pasted image 20230320123343.png]]
```

causes to flash the reference map and then remain empty. Removing the pasted image line fixes the plugin.

**Comment by anoopkcn** [comment]
Hi @jankap This issue was also related to another one #26. This should be fixed now please update the plugin
