### ISSUE TITLE
Long hangs

### ISSUE THREAD

**Issue by huachuman** [anoopkcn/obsidian-reference-map#28]
This plugin is causing long hangs on Obsidian. I presume it's because I have a large library. Obsidian will randomly hang for 30 seconds to minutes at a time while in use. This was fixed by disabling the plugin. Upon re-enabling the plugin, Obsidian hangs for a long time. Restarting obsidian with the plugin enabled adds a very long delay. I have an M2 nVME and plenty of unused DDR5 RAM so I doubt it's my hardware.

**Comment by huachuman** [comment]
Any idea?

**Comment by anoopkcn** [comment]
hi @huachuman I have been a bit busy these days. But I will have free time to look at it in a few days

**Comment by huachuman** [comment]
Of course, thank you so much for addressing this. It is such a shame because the plugin is otherwise absolutely brilliant and so well made. I'm not really a programmer but please let me know if there's anything I can do to help you with this. I already tried looking in the console but didn't find much.

**Comment by anoopkcn** [comment]
hi @huachuman I found the bug. 
Can I ask how big your library is?(you can give me the size of the file)

**Comment by anoopkcn** [comment]
the plugin checks if your bib file is changed or not if it is changed then it loads the file again to get the new entries. it looks like the native function that I am using to check the stats of the file is unreliable(depending on the platform). 
The two solutions I can think of are:
1) if the bib/json file exceeds a certain size one has to refresh the library manually
2) all libraries regardless of the size should be refreshed manually after you add a new entry in zotero
I will also think about if I can make the behaviour consistent
If you have suggestions please let me know

**Comment by huachuman** [comment]
My .bib is 10.7mb if that helps any.

**Comment by anoopkcn** [comment]
This should be resolved by now. There is also a new option to pull bibliography from Zotero directly. Without needing any file exports.

**Comment by anoopkcn** [comment]
Related to #35
