### ISSUE TITLE
FR: Search the citation/references

### ISSUE THREAD

**Issue by chrisgrieser** [anoopkcn/obsidian-reference-map#3]
I think being able to search through the list of references/citations would make a lot of sense for this plugin?

**Comment by anoopkcn** [comment]
Yes, indeed. Sorting, Settings and Searching are the features in my list for implementation.

**Comment by anoopkcn** [comment]
This feature is implemented in the latest release version `0.5.0`. Please check it out

**Comment by chrisgrieser** [comment]
Thank you 😊 

So I tried the feature out, and it seems the search is broken: in this gif, I search for "Latour" and "Lederer", which are among the references (as can be seen at the beginning), but as soon as I type out the names, the respective entries vanish?

![2023-01-05 14 14 40](https://user-images.githubusercontent.com/73286100/210788482-9c8a80ab-597c-4a19-8892-ecfb1078edab.gif)

**Comment by anoopkcn** [comment]
Yes, I am fixing this issue now.  Author names are not included in the search at the moment.

**Comment by anoopkcn** [comment]
It should be fixed now. Checkout the latest version

**Comment by chrisgrieser** [comment]
yep, works fine now, thank you!
