### ISSUE TITLE
Support DOI search in Search Reference

### ISSUE THREAD

**Issue by wenbopeng** [anoopkcn/obsidian-reference-map#33]
**Is your feature request related to a problem? Please describe.**
Support DOI search in Search Reference
![image](https://github.com/anoopkcn/obsidian-reference-map/assets/74350447/b61a210a-b2fb-46dd-b354-a688d0ee0774)

**Describe the solution you'd like**
It would be great to support retrieving doi, like `10.1111/1475-6765.12529`, or `doi:10.1111/1475-6765.12529` or `https://doi.org/10.3390/e20110814`

**Comment by braeden-muller** [comment]
I always approve of more quality of life features, but what is the use-case for this?

**Comment by wenbopeng** [comment]
> I always approve of more quality of life features, but what is the use-case for this?

I like the function of quickly obtaining bibliography, doi search is more accurate than keyword search, and I can copy the information I want with one click.

**Comment by anoopkcn** [comment]
Hi the feature is implemented and available in the version `1.2.7` and above. You can now also select a text containing a ID and initiate the search

**Comment by wenbopeng** [comment]
> Hi the feature is implemented and available in the version `1.2.7` and above. You can now also select a text containing a ID and initiate the search

Unbelievable, awesome!
