### ISSUE TITLE
[FR] Pull bibliography from Zotero

### ISSUE THREAD

**Issue by wwjCMP** [anoopkcn/obsidian-reference-map#35]
Read data directly from Zotero library instead of using exported CSL file, just like plugins zotlit and pandoc reference list plugin, by using something like [@citekey]

**Comment by anoopkcn** [comment]
Hi @wwjCMP 
I implemented this feature similar to `pandoc reference list`. You can now connect directly to Zotero without exporting the bibliography file. Please check out the lastest release version

**Comment by wwjCMP** [comment]
It worked perfectly, thank you for your outstanding work. 

What is more，when a file contains both citekey and doi, it may will result in duplicate bibliographic information. Eliminating duplicate references is not necessary, but it would be better if it could be achieved.

**Comment by anoopkcn** [comment]
If it's not too much trouble, can you open a new issue for resolving the duplicate bibliographic information? 
You can copy the last sentence from your comment.
