### ISSUE TITLE
[FR] Eliminating duplicate references

### ISSUE THREAD

**Issue by wwjCMP** [anoopkcn/obsidian-reference-map#36]
When a file contains both citekey and doi, it may result in duplicate bibliographic information. Eliminating duplicate references is not necessary, but it would be better if it could be achieved.

**Comment by anoopkcn** [comment]
Hi @wwjCMP This is fixed. You can get it at the latest version.

**Comment by anoopkcn** [comment]
Sorry there is an other bug

**Comment by anoopkcn** [comment]
Hi @wwjCMP ,  this is fixed in the latest version. You have to turn on the `Remove Duplicate Cards` in the settings tab
