### ISSUE TITLE
Port of zotero is not available in settings

### ISSUE THREAD

**Issue by adrientaudiere** [anoopkcn/obsidian-reference-map#38]
First, thank you so much for this plugin.

I can't integrate zotero and I can't try to change my zotero port which seems to be 23119.

![image](https://github.com/anoopkcn/obsidian-reference-map/assets/6680165/0a4f1025-f24a-40fd-b6de-cf9a8b8252bd)

-  Mx Linux
-  Obsidian version 1.4.16
-  Plugin version 1.5.5

**Comment by anoopkcn** [comment]
Hi @adrientaudiere,  You need a running instance of Zotero to connect to it. Zotero should also have plugin called `better bibtex plugin`. 
Steps:
- Start Zotero
 - Install `Better Bibtex` [plugin](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.136) in Zotero
 - Go to Reference Map settings in Obsidian 
 - Click on the retry button
 - The rest of the options should show up for setting port and selecting your libraries
 - Select your libraries (Usually called: My Library)

Please let me know if it works

**Comment by anoopkcn** [comment]
You only need  Zotero open once when you set it up.

**Comment by adrientaudiere** [comment]
Hi @anoopkcn. I am sorry I forgot to install the `Better bibtex` plugin. It works perfectly.
