### ISSUE TITLE
Account for doi ending with a point

### ISSUE THREAD

**Issue by adrientaudiere** [anoopkcn/obsidian-reference-map#39]
Some bibliography style put a "." at the end of doi. Those doi are not see by reference-map plugin.

e.g.
 
https://doi.org/10.1371/journal.pone.0131069. -> not worknig

https://doi.org/10.1371/journal.pone.0131069 -> work

Thanks for your work!

**Comment by anoopkcn** [comment]
Hi, @adrientaudiere This issue is fixed in the latest version of the plugin. Update the plugin and attempt the same. Please let me know if it works

**Comment by adrientaudiere** [comment]
Hi @anoopkcn, thanks for your prompt answer. I tried the version 1.5.7 of your plugin, but nothing changed on my side. I also updated my zotero version to 6.0.30.

**Comment by adrientaudiere** [comment]
Thanks a lot. It works!
