### ISSUE TITLE
FR: Add support to DOIs that are part of links

### ISSUE THREAD

**Issue by pcuellar** [anoopkcn/obsidian-reference-map#4]
I import papers via Zotero Integration which bring DOIs as links so that I can quickly refer to the web version of each paper. However, your plugin does not take a DOI that is part of a markdown link _a-la_ `[DOI#](link-to-DOI)`. It would be great to have this feature which will save those of us using this workflow having to reformat hundreds of files. Thanks!

**Comment by anoopkcn** [comment]
Hi, Thanks for the feedback. I use my plugin [zotero-annotations](https://github.com/anoopkcn/obsidian-zotero-annotations) to import notes and annotations from Zotero, which formats the DOI in a specific way. However,  **I will implement a solution to your problem soon**

**Comment by anoopkcn** [comment]
I fixed this issue; please check the release version [0.3.4](https://github.com/anoopkcn/obsidian-reference-map/releases/tag/0.3.4). Let me know if this works; I will close the issue if it does.

**Comment by pcuellar** [comment]
Thanks for looking into this. Unfortunately, it does not seem to work for me. See screenshots attached. I tried it on a sandbox vault and it didn't work either. No errors on console

<img width="1267" alt="Screenshot 2023-01-03 at 7 27 59 PM" src="https://user-images.githubusercontent.com/20482146/210463612-9f4bcf8f-05e0-489b-adf2-7a3a0a46e67d.png">
<img width="1271" alt="Screenshot 2023-01-03 at 7 28 24 PM" src="https://user-images.githubusercontent.com/20482146/210463614-e0f17eec-d6a2-4015-be87-595af2a57085.png">

**Comment by anoopkcn** [comment]
Hi, Thanks for the screenshots. Hopefully, I fixed it this time. Checkout the version [0.3.5](https://github.com/anoopkcn/obsidian-reference-map/releases/tag/0.3.5)

**Comment by pcuellar** [comment]
Can confirm this is working. Thanks for implementing this 🔥

**Comment by anoopkcn** [comment]
There was a bug in matching multiple DOI links in the same file. it is fixed now. You might want to get the latest version
