### ISSUE TITLE
minor FR: label citations/reference count

### ISSUE THREAD

**Issue by chrisgrieser** [anoopkcn/obsidian-reference-map#5]
especially now with the label removed (which was good for space-saving!) I now cannot tell which of the two numbers is citations, and which is references. 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/73286100/210590401-ee9bbdae-9aca-438d-a92c-be1d714a2449.png">

as a solution, you could label then (number + `r`, number + `c`) or add a tooltip to it maybe?

**Comment by anoopkcn** [comment]
I plan to add the labels as a search placeholder, which opens up after clicking the reference/citations count. As you mentioned, I could also add a tooltip. But I find tooltips annoying. In that case, perhaps I can add a settings option to disable the tooltip.

**Comment by anoopkcn** [comment]
Hi @chrisgrieser,  The search field placeholder tells you if it is Citations or References. I made the changes and  this is how it looks now:

<img width="318" alt="orm-demo" src="https://user-images.githubusercontent.com/14111873/210779071-73c59f54-d1f4-4d37-b9a0-7dcc688e3a46.png">

**Comment by chrisgrieser** [comment]
wow, using a the placeholder is such a smart idea. subtle and space-saving, I love it. Thanks!
