### ISSUE TITLE
Connect with latest Zotero

### ISSUE THREAD

**Issue by wwjCMP** [anoopkcn/obsidian-reference-map#50]
<img width="587" alt="Snipaste_2024-02-12_08-09-39" src="https://github.com/anoopkcn/obsidian-reference-map/assets/32979859/be3bdafa-e07a-4d03-8582-b8177b617edb">

<img width="233" alt="Snipaste_2024-02-12_08-15-10" src="https://github.com/anoopkcn/obsidian-reference-map/assets/32979859/25551a34-bc5d-4500-bd24-7dad94152e64">

It was failed to connect with the latest Zotero.

**Comment by anoopkcn** [comment]
Isn't this Zotero version a developer beta? I will check what changed but if it is a change with betterbibtex plugin in Zoteo then I won't be able to fix it before they fix it

**Comment by wwjCMP** [comment]
My bad, I forgot to install the BetterBibTeX plugin on the new computer for Zotero.
