### ISSUE TITLE
Reference Map Graph note loading

### ISSUE THREAD

**Issue by nomadphase** [anoopkcn/obsidian-reference-map#55]
**Describe the bug**

Sometimes the Reference Map Graph will not load, giving me this error message

![image](https://github.com/anoopkcn/obsidian-reference-map/assets/72380765/8ae31eac-6f38-4dec-a8c5-4217bbe49525)

**To Reproduce**

This is despite the plugin being targeted to a markdown file with valid identifiers (DOI)

![image](https://github.com/anoopkcn/obsidian-reference-map/assets/72380765/ece894e5-129b-4169-8088-3c545bb87fc4)

1. Open '.'
2. Type '....'

**Console output**

![image](https://github.com/anoopkcn/obsidian-reference-map/assets/72380765/c8ea642c-fc69-45e7-8b8a-003c2ba86403)

![image](https://github.com/anoopkcn/obsidian-reference-map/assets/72380765/e0f2c9f8-feca-4f5b-994a-50914109fb2a)

**Expected behavior**

I expect the reference map graph to load up showing clusters of citations with purple and green nodes.

**Screenshots**

**Platform**

-   OS: [Windows 11 Home 23H2]
-   Obsidian version [v1.6.1; installer version v1.5.8]
-   Plugin version [1.81]

**Additional context**

This problem is intermittent. It was not occurring earlier today, but has occurred previously.

**Comment by nomadphase** [comment]
Okay, so weird - it has just resolved itself, with no action taken by me.

![image](https://github.com/anoopkcn/obsidian-reference-map/assets/72380765/0721ac04-8740-43a0-b140-b1742d82a598)

**Comment by anoopkcn** [comment]
It looks like the original issue was reference-map unable to connect to Zotero. If the problem re-occurs, there is a refresh function in the command palette `Reference Map: Refresh View and Library`. You can run that command and send me the console log.
