### ISSUE TITLE
Feat: Find reference via title of the note

### ISSUE THREAD

**Issue by HEmile** [anoopkcn/obsidian-reference-map#6]
Hi there! My literature notes have the note's title as the paper's title. Is it possible with the Semantic Scholar API to find the reference via the note's title (as an option)? Or does the API not support full-text search/matching?

**Comment by anoopkcn** [comment]
Hi @HEmile, It is possible to search with titles or keywords. This would be an interesting feature to implement. I will look into it. Thanks for the suggestion.

**Comment by HEmile** [comment]
That's great to hear :) Would be super useful for me, as I won't have to refactor my vault to be compatible with this plugin. Thanks!

**Comment by anoopkcn** [comment]
I would have to identify the title with some key like `title: .....`; otherwise, I would have to send an API request for each sentence in the current document, with would not be ideal since there is a limit on API requests per second. If you have some ideas about this, it would be nice.

**Comment by HEmile** [comment]
That's true. In my case, the title is the note's title itself, so it would always be the same.

**Comment by anoopkcn** [comment]
I looked into the API. At the moment it only accepts keyword searches. If we just take the file name as a query and make it into a keyword search(which is easy to do), the problem is that the query will return everything containing the words in the file title( since it will also look for abstracts of papers when returning the results) So; one might end up with a bunch of unrelated papers, especially for generic file names(assuming you vault also contains other notes).

**Comment by HEmile** [comment]
Ah I see, I was worried there wouldn't be a full title search, haha. I'd be very happy with a list of possible references and having to manually select the correct one, if that's an option.

**Comment by anoopkcn** [comment]
@HEmile, I added this feature in the [latest release](https://github.com/anoopkcn/obsidian-reference-map/releases) of the plugin. Please check it out. 

You can enable this feature in the settings tab->**Search References**(default=OFF). I also put a field in the settings to set the limit of query results(default=3).  I am unsure how likely you will find the paper you want in the results.  I will try to find a better solution but at the moment I hope you can use this.

**Comment by HEmile** [comment]
I just tried it and for everything I tried the correct reference came on top :) So I limited it to 3. It seems to work super well, thank you! I've considered making a plugin like this for ages, and I'm so happy someone did now!! Thank you :)
