### ISSUE TITLE
export references to clipboard

### ISSUE THREAD

**Issue by grant-m-s** [anoopkcn/obsidian-reference-map#8]
A lot of the papers I read have a lot of overlap in the references they use. It would be useful to copy the list of references generated to the clipboard (ideally in a customisable format i.e [[title - Author Year]] , as that's how my notes are titled for papers). That way it would be easy to see which notes I already have created as well as see which papers have the most overlap.

Could you see this being a useful addition?

Cheers,
Grant

**Comment by anoopkcn** [comment]
Hi @grant-m-s, That's an interesting idea.  This way one will be able to visualize the connections between references using the graph view.

**Comment by anoopkcn** [comment]
I implemented this feature. It is in the latest release version. 
You have to enable this in the settings, handled by the `Metadata Three Button`(disabled by default). The setting would look something like this:
<img width="786" alt="references_batch_copy" src="https://user-images.githubusercontent.com/14111873/211553740-12e29fa8-b2c0-45f4-96e0-d91b17e053d8.png">
If you don't enable the batch copy, the button will only copy the index card details in the specified template format.
