### ISSUE TITLE
Citekey references don't show up

### ISSUE THREAD

**Issue by jankap** [anoopkcn/obsidian-reference-map#9]
First of all: great plugin, I already love it.

While DOI detection works fine, I have an issue using the cite keys, please see the screenshots:

![image](https://user-images.githubusercontent.com/12893844/211821925-f62e0a6b-16e7-45a4-b407-8f36ea680af9.png)
![image](https://user-images.githubusercontent.com/12893844/211821991-45db7be5-657f-493b-a43b-8b3e2e9e92fb.png)

The CSL JSON file is exported via Zotero:

![image](https://user-images.githubusercontent.com/12893844/211822492-0eaf276d-455a-4632-ae2d-944bed68f368.png)

I tried both, `Better CSL JSON` and `BetterBibTex JSON`, both files seem not to work. Am I doing something wrong?

[Full.zip](https://github.com/anoopkcn/obsidian-reference-map/files/10392908/Full.zip)

Thanks!

**Comment by anoopkcn** [comment]
Hi, Try the latest release. The issue was due to the `citekey` only allowing alphanumeric characters(your keys included a dot`.`). Now it also allows all characters except `(` , `]` , `*` and spaces. 

So your issue should be fixed by now

**Comment by anoopkcn** [comment]
If it works, please close the issue.

**Comment by jankap** [comment]
Awesome, works now. Thanks :)
